AWSTemplateFormatVersion: '2010-09-09'

Description: A template to create an S3 bucket

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: bucket-created-by-cf-kjbkabkefa

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyS3Bucket
